spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3310/library
    driver-class-name: com.mysql.cj.jdbc.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true
  mvc:
    format:
      date: yyyy-MM-dd
#      date-time: yyyy-MM-dd HH:mm:ss
#      time: HH:mm:ss
#  jackson:
#    time-zone: Etc/GMT-3